version: '3'
services:

    postgres:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: speedrun
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

    api:
        build:
            context: .
            dockerfile: "./Dockerfile"
        ports: 
            - 8080:8080
        depends_on: 
            - 'postgres'
        # command: ["sh", "-c", "cd /go/src/cmd && go run main.go"]
        command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
        volumes:
            - .:/go/src/
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_HOST: "postgres"
            POSTGRES_DATABASE: "speedrun"
            HOST: "0.0.0.0"
            PORT: 8080
            TZ: Asia/Tokyo
            ENV: "develop"